import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import NavBarWrapper from "@/components/navbarWrapper";
import Link from "next/link";
import { Toaster as ToasterShadcn } from '../components/ui/toaster';
import "react-big-calendar/lib/css/react-big-calendar.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} flex min-h-screen w-full flex-col`}>
        <ThemeProvider attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange

        >
          <Toaster richColors closeButton position="top-left" />
          <ToasterShadcn />
          {/* Headers */}

          <>
            <NavBarWrapper />
          </>

          <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-8">
            {children}
          </main>

          <footer className="w-full flex items-center justify-center py-3">
            <Link
              className="flex items-center gap-1 text-current"
              href="https://mg.linkedin.com/in/spat-port-toamasina-4607b519a"
              title="LinkedIn Connect"
            >
              <span className="text-default-600">Powered by</span>
              <p className="text-primary">Spray Info</p>
            </Link>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
