# compose.yml
services:
  rustapp:
    container_name: rustapp
    build:
      context: ./backend
      dockerfile: rust.dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/leave_management
    ports:
      - "8080:8080"
    depends_on:
      - db   
  
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leave_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  
volumes:
  pgdata: {}