//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "conge")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id_cong: String,
    pub id_empl: String,
    pub date_dmd_cong: DateTime,
    pub motif_cong: String,
    pub date_deb_cong: DateTime,
    pub date_fin_cong: DateTime,
    #[sea_orm(column_type = "Decimal(Some((4, 1)))")]
    pub nb_jour_cong: Decimal,
    pub status_cong: String,
    pub date_trait_cong: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::employe::Entity",
        from = "Column::IdEmpl",
        to = "super::employe::Column::IdEmpl",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Employe,
}

impl Related<super::employe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Employe.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
