//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::conge::Entity as Conge;
pub use super::departement::Entity as Departement;
pub use super::employe::Entity as Employe;
pub use super::solde::Entity as Solde;
